### ISSUE TITLE
SS4.1: Gridfield sorting not working any more with text-target-lenght installed

### ISSUE THREAD

**Issue by wernerkrauss** [jonom/silverstripe-text-target-length#16]
I ran into the same  issue like https://github.com/symbiote/silverstripe-gridfieldextensions/issues/246 today when I wasn't able to sort a gridfield and got a js error. Then I tried out the undefinedoffset sorting module, which threw another error, but works fine on a similar project (where text-target-length and some other modules are not required).

After disabling this extension, it started to work again.

Other gridfield related modules installed in this project:
* userforms
* focuspoint
* bulkuploader
* blog
* gridfieldextensions

HTH

**Comment by jonom** [comment]
Judging by the thread in that module the problem is not triggered only by the presence of this module so I don't think anything needs to be fixed here - but I'll leave it open for now. Can you please close if a fix is introduced elsewhere.

**Comment by wernerkrauss** [comment]
@jonom sure, but I guess your module also does some JavaScript "magic" that is not compatible with either SS4 or SS4.1's backend and/or those modules. So - if we can find _what_ is causing that error, it can also be fixed it in this module.

**Comment by a2nt** [comment]
If u will remove 2 lines at JonoM\SilverStripeTextTargetLengt\SilverStripeTextTargetLengt:
```
Requirements::javascript('silverstripe/admin:thirdparty/jquery/jquery.js');
Requirements::javascript('silverstripe/admin:thirdparty/jquery-entwine/dist/jquery.entwine-dist.js');
```
everything will work ok. The issue produced by overwriting core CMS libraries

**Comment by jonom** [comment]
Interesting. So where are those libs loaded from in the CMS if not from there? Are they bundled in to a different js file?

**Comment by a2nt** [comment]
you don't need to load them cuz it's being loaded at the LeftAndMain already.
And it comes from /resources/vendor/silverstripe/admin/client/dist/js/vendor.js
Take a look at chrome dev-console:
![screenshot from 2018-05-29 00-16-17](https://user-images.githubusercontent.com/672794/40624301-f488df3a-62d5-11e8-80cd-56cfb461ad6b.png)

**Comment by jonom** [comment]
Fixed (hopefully) with https://github.com/jonom/silverstripe-text-target-length/pull/17
