### ISSUE TITLE
HTMLEditorField count isn't updated live

### ISSUE THREAD

**Issue by jonom** [jonom/silverstripe-text-target-length#2]
The underlying textarea field behind any HTMLEditorField only registers a change event once you click / change focus outside of TinyMCE. This problem affects the Save/Publish buttons in the CMS too, so I suspect that updating the behaviour in the CMS to register changes more often for these fields would fix both of these issues.

Related: https://github.com/silverstripe/silverstripe-framework/pull/3592

**Comment by tractorcow** [comment]
Have you tested this in framework 4.0? It has been updated to tinymce 4 recently and uses a new update mechanism.

**Comment by jonom** [comment]
Tested in 4.0 just now but this module isn't compatible at the moment - need to update `tinyMCE.getInstanceById()` to whatever TinyMCE 4 equivalent is.

**Comment by tractorcow** [comment]
Ah I see. ;D

**Comment by ZaneA** [comment]
Hi guys, I was able to solve this in 3.x by changing the `onadd` method in `text-target-length.js`:

```js
onadd: function() {
	// Insert extra markup
	var field = $(this);
	field.parent().append('<p class="target-length-count">');

	// Hook TinyMCE onKeyUp
	if (field.hasClass('htmleditor')) {
		tinyMCE.onAddEditor.add(function (mgr, ed) {
			if (ed.id !== field.attr('ID')) return;

			ed.onKeyUp.add(function (ed, e) {
				field.updateCount();
			});
		});
	}

	this.updateCount();
},
```

Let me know if I should submit a pull-request, maybe there is a cleaner way to handle this :)

**Comment by jonom** [comment]
Hey @ZaneA a PR would be great thanks :) I'm on vacation but I'll try to review it soon
