### ISSUE TITLE
SS 4.0 HTMLEditorField support

### ISSUE THREAD

**Issue by jonom** [jonom/silverstripe-text-target-length#3]
Need to update `tinyMCE.getInstanceById()` to whatever TinyMCE 4 equivalent is.

**Comment by zanderwar** [comment]
This is your fix, however you're faced with a race-condition, tinymce.js is added after `text-target-length.js` thus the editors havn't been instantiated when this method is called, so `editor` is always `null`.

```
getText: function() {
	var field = $(this);
	if (field.hasClass('htmleditor')) {
		var editor = tinymce.get(field.attr('id'));
		if (editor !== undefined && editor !== null) {
			return $(editor.getContent()).text();
		} else {
			return $('<div />').html(field.val()).text();
		}
	}
	return field.val();
}
```

Furthermore onchange or any other events don't appear to fire, maybe the textarea isn't written to until save

**Comment by zanderwar** [comment]
There's also an issue with how entwine is setup or something, trying to get it fixed but the script only fires after an actual refresh, if you click on another page to edit it the functionality of this module isn't readded until you refresh

**Comment by DrMartinGonzo** [comment]
I did something similar sometimes ago.
My solution wad to create a plugin for Tinymce, maybe this would help you ?
Here is my code :
```js
/* eslint-env browser */
/* globals tinymce, ss */

import jQuery from 'jquery'; /* eslint-disable-line */


tinymce.PluginManager.add('charcount', (editor) => {
  editor.on('init', () => {
    let statusBarCharCount;
    let statusbar;

    function getCharacterLength() {
      let text = editor.getContent({ format: 'text' });
      // trim and transform newlines ("\n" has a length of 2) to spaces (length = 1)
      text = text.trim().replace(/(\n)+/g, ' ');
      return text.length;
    }

    function getStatusBarText() {
      const characterLength = getCharacterLength();
      const limit = editor.targetElm.getAttribute('data-maxchar');
      let text = `${ss.i18n._t('CHARCOUNT.CHARACTERS')}: {0}`;
      if (limit) {
        const charCountSpan = statusbar.$el.find('.mce-charcount')[0];
        if (characterLength > limit) {
          charCountSpan.style.color = 'red';
        } else {
          charCountSpan.style.color = '';
        }
        text += ` / ${limit}`;
      }
      return [text, characterLength];
    }

    function update() {
      statusBarCharCount.text(getStatusBarText());
    }

    statusbar = editor.theme.panel && editor.theme.panel.find('#statusbar')[0];
    if (statusbar) {
        statusbar.insert({
          type: 'label',
          name: 'charcount',
          classes: 'wordcount charcount',
          disabled: editor.settings.readonly
        }, 0);

        statusBarCharCount = editor.theme.panel.find('#charcount');
        update();

        editor.on('keyup setcontent beforeaddundo', () => {
          update();
        });
    }
  });
});
```

It is then activated via :
```php
HtmlEditorConfig::get('cms')
->enablePlugins([
    'template',
    'fullscreen',
    'charcount' => ModuleResourceLoader::resourceURL(<path-to-js-file>),
])
```

**Comment by jonom** [comment]
Thanks for your input guys :) I may not have a change to look at this for a while but if anyone produces a fix please open a pull request

**Comment by J-Pielage** [comment]
Hi! Is there any planning of this issue being fixed soon?

**Comment by jonom** [comment]
@J-Pielage I'm not planning on looking at this personally, but will gladly review a pull request.

**Comment by J-Pielage** [comment]
> getText: function() {
> 	var field = $(this);
> 	if (field.hasClass('htmleditor')) {
> 		var editor = tinymce.get(field.attr('id'));
> 		if (editor !== undefined && editor !== null) {
> 			return $(editor.getContent()).text();
> 		} else {
> 			return $('<div />').html(field.val()).text();
> 		}
> 	}
> 	return field.val();
> }

@jonom This code has not been added yet? the counter will appear with that. I can add it and create a pull request

**Comment by jonom** [comment]
Nope, no one has added it. @zanderwar indicated above that it was an incomplete solution so more work would be required to make it reliable.
